### ISSUE TITLE
UnityModManager.modsPath should be used to get the settings.json path

### ISSUE THREAD

**Issue by lucianposton** [Holic75/KingmakerProperFlanking#1]
https://github.com/Holic75/KingmakerProperFlanking/blob/1fb5f11b1ade1c2d6f1987509804715643f7daf7/ProperFlanking20/Main.cs#L30

Please use `UnityModManager.modsPath` in order to get the `Mods` directory. It isn't necessarily in the current working directory, `Pathfinder Kingmaker/game`. If the user selected `Pathfinder Kingmaker` as the path when setting up unity mod manager, for example, the mod fails to load with a file not found exception.

**Comment by Holic75** [comment]
fixed in 1.16c
